fail_fast: false
minimum_pre_commit_version: "2.6.0"
ci:
  autofix_commit_msg: 'chore(pre-commit.ci): Auto fixes [...]'
  autoupdate_commit_msg: 'chore(pre-commit.ci): Auto update of pre-commit hooks'

repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/terraform-docs/terraform-docs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: 212db41760d7fc45d736d5eb94a483d0d2a12049  # frozen: v0.16.0
    hooks:
      - id: terraform-docs-go
        args:
          - "--config=.terraform-docs.yaml"
          - "--lockfile=false"
          - "--recursive"
          - "--recursive-path=examples/"
          - "./"
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
