# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: Create Release

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - 'main'
      - 'rc/*'
      - 'rc'
      - 'beta/*'
      - 'beta'
      - 'alpha/*'
      - 'alpha'

jobs:
  release:
    name: Shared Workflow
    uses: sassy-bulldog/.github/.github/workflows/release.yml@v0.2.2 # x-release-please-version
    secrets: inherit
